### ISSUE TITLE
Could you show as an example of deploying with multi-container docker

### ISSUE THREAD

**Issue by jasjuang** [dkarchmer/aws-eb-docker-django#4] opened 2016-09-13 00:13 UTC
Thanks for putting this up. It works like a charm. I am wondering could you put up a multi-container docker example for Django? I am having trouble to get it working. Thanks

**Comment by dkarchmer** [comment] 2016-09-13 21:29
Sorry, that's out of scope for this project. I have personally not found a real reason to use multi-container, as I usually deploy django with other self managed services (e.g. RDS for Postgress, ElasticCache for Redis, etc.).

**Closed as completed by dkarchmer** 2016-09-13 21:29 UTC

**Comment by jasjuang** [comment] 2016-09-13 21:39
Thanks for your response. The reason I think I need to use multi-container is because I need to spawn multiple worker (celery) processes and I can't figure out how to do it with a single container.

**Comment by dkarchmer** [comment] 2016-09-13 21:52
Fair enough, but using EB may not be the right solution for that, as each instance will be a duplicate of each other (it will contain all containers). If you need to launch 4 servers, you will also launch 4 celery nodes, and vice versa. This is why I stayed away from celery when using EB, and instead moved all my background tasks to either AWS Lambda (serverless) or in some cases, using the vanilla EB worker tier, which requires that you manually create SQS messages to be processed by the worker. Not bad if you only need to handle a couple of background processes. You loose celery's management, but EB will manage it well, including auto-scaling. If you can do it all with AWS Lambda, that is the way to go.

**Comment by jasjuang** [comment] 2016-09-13 21:55
I will look into it. Thanks a lot for the advice!
